config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("rps.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("game/", include("rps.gameplay.urls", namespace="gameplay")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

rps/gameplay/urls.py
from django.urls import path

from rps.gameplay.views import index, new_game, play

app_name = "gameplay"
urlpatterns = [
    path("", view=index, name="index"),
    path("<uuid:game_uuid>/play/", view=play, name="play"),
    path("new/<int:game_type>/", view=new_game, name="new_game"),
]

templates/pages/home.html
{% extends "base.html" %}

{% block content %}
  <h2 class="text-center">Welcome to Rock, Paper, and Scissors</h2>
  <div class="row">
    <div class="col-4 text-center">
      <i class="fa-regular fa-hand-back-fist fa-10x" title="Rock"></i>
    </div>
    <div class="col-4 text-center">
      <i class="fa-regular fa-hand fa-10x" title="Paper"></i>
    </div>
    <div class="col-4 text-center">
      <i class="fa-regular fa-hand-peace fa-10x" title="Scissors"></i>
    </div>
  </div>
  <div class="row mt-3">
    <a href="{% url 'gameplay:index' %}" class="btn btn-primary btn-large btn-block">Shall We Play A Game?</a>
  </div>
{% endblock content %}