config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("rps.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("game/", include("rps.gameplay.urls", namespace="gameplay")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

rps/gameplay/urls.py
from django.urls import path

from rps.gameplay.views import index, new_game, play

app_name = "gameplay"
urlpatterns = [
    path("", view=index, name="index"),
    path("<uuid:game_uuid>/play/", view=play, name="play"),
    path("new/<int:game_type>/", view=new_game, name="new_game"),
]

rps/gameplay/models.py
import logging
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from rps.utils import constants

User = get_user_model()
logger = logging.getLogger(__name__)


class Game(models.Model):
    PLAYER_VERSUS_PLAYER = 1
    PLAYER_VERSUS_COMPUTER = 2
    GAME_TYPE_CHOICES = (
        (PLAYER_VERSUS_PLAYER, "Player vs. Player (PVP)"),
        (PLAYER_VERSUS_COMPUTER, "Player vs. Computer (AI)"),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    game_type = models.IntegerField(
        "Game Type", choices=GAME_TYPE_CHOICES, default=PLAYER_VERSUS_PLAYER
    )

    player_one = models.ForeignKey(
        User,
        related_name="games_as_player_one",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    player_two = models.ForeignKey(
        User,
        related_name="games_as_player_two",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )

    created_at = models.DateTimeField("Created At", auto_now_add=True)
    modified_at = models.DateTimeField(
        "Last Player Turn", auto_now=True, blank=True, null=True
    )
    completed_at = models.DateTimeField("Game Completed At", blank=True, null=True)

    @property
    def game_winner_info(self):
        """Return the winner of a game
        Since the computer player is not an actual user, we need to determine who won based on the results of the Turns
        :return: User who won game, else None
        """
        winning_player = None
        name = None
        if self.turns.filter(turn_result=GameTurn.PLAYER_ONE_WINS).count() > 0:
            if self.player_one is None:
                name = "Computer"
                winning_player = None
            else:
                name = self.player_one.name
                winning_player = self.player_one
        elif self.turns.filter(turn_result=GameTurn.PLAYER_TWO_WINS).count() > 0:
            if self.player_two is None:
                name = "Computer"
                winning_player = None
            else:
                name = self.player_two.name
                winning_player = self.player_two

        # if there is a winning player, return their info
        if name is not None:
            return {
                "name": name,
                "user": winning_player,
            }

        # there is not yet a winning player!
        return None

    def which_players_turn(self):
        """Determine which player's turn it is.
        If there are no turns, or the same number of turns for each player has been completed,
        either player can play, so we return None

        If Player one has played more turns, then it's player two's turn
        Otherwise it's Player One's turn
        """
        # if there have been no turns made, either player can play
        if self.turns.count() == 0:
            return None

        player_one_turn_count = self.turns.filter(
            player_one_choice__isnull=False
        ).count()
        player_two_turn_count = self.turns.filter(
            player_two_choice__isnull=False
        ).count()

        player_user = None
        if player_one_turn_count == player_two_turn_count:

            return None

        if player_one_turn_count > player_two_turn_count:
            if self.player_two is None:
                player_name = "Computer"
            else:
                player_name = self.player_two.name
                player_user = self.player_two

        else:
            if self.player_one is None:
                player_name = "Computer"
            else:
                player_name = self.player_one.name
                player_user = self.player_one

        return {
            "name": player_name,
            "user": player_user,
        }

    def get_absolute_url(self):
        """Get url for game's play view

        Returns:
            str: URL for game's play view.

        """
        return reverse("gameplay:play", kwargs={"uuid": self.id})

    def __str__(self):
        return str(self.id)


class GameTurn(models.Model):
    TURN_PLAY_CHOICES = tuple(
        [
            (key, option["name"])
            for key, option in constants.GAMEPLAY_OPTIONS_DICT.items()
        ]
    )

    PLAYER_TIE = 1
    PLAYER_ONE_WINS = 2
    PLAYER_TWO_WINS = 3
    TURN_OUTCOME_CHOICES = (
        (PLAYER_TIE, "Tie"),
        (PLAYER_ONE_WINS, "Player One Wins"),
        (PLAYER_TWO_WINS, "Player Two Wins"),
    )

    game = models.ForeignKey("Game", related_name="turns", on_delete=models.CASCADE)
    player_one_choice = models.IntegerField(
        "Player One Choice", choices=TURN_PLAY_CHOICES, blank=True, null=True
    )
    player_two_choice = models.IntegerField(
        "Player Two Choice", choices=TURN_PLAY_CHOICES, blank=True, null=True
    )

    turn_result = models.IntegerField(
        "Turn Outcome", choices=TURN_OUTCOME_CHOICES, blank=True, null=True
    )

    created_at = models.DateTimeField("Created At", auto_now_add=True)

    def __str__(self):
        if self.game.player_one is not None:
            player_one_name = self.game.player_one.name
        else:
            player_one_name = "Computer"

        if self.game.player_two is not None:
            player_two_name = self.game.player_two.name
        else:
            player_two_name = "Computer"

        if self.player_one_choice is not None:
            player_one_info = f"played {self.get_player_one_choice_display()}"
        else:
            player_one_info = "has not yet picked a choice"

        if self.player_two_choice is not None:
            player_two_info = f"played {self.get_player_two_choice_display()}"
        else:
            player_two_info = "has not yet picked a choice"

        return f"{player_one_name} {player_one_info} vs {player_two_name} {player_two_info}"

rps/gameplay/forms.py
import logging
import random

from django import forms
from django.contrib.auth import get_user_model
from django.utils import timezone

from rps.gameplay.models import Game, GameTurn
from rps.utils import constants

User = get_user_model()
logger = logging.getLogger(__name__)


class UserTurnForm(forms.ModelForm):
    """The form used for a user playing their part of the game"""

    user = None
    game = None

    class Meta:
        model = GameTurn
        fields = ["player_one_choice", "player_two_choice"]

    def __init__(self, *args, **kwargs):
        # pass the logged in user and the game into the form for security/non-cheat reasons
        self.user = kwargs.pop("user")
        self.game = kwargs.pop("game")
        super().__init__(*args, **kwargs)

        if self.user == self.game.player_one:
            self.fields["player_two_choice"].widget = forms.HiddenInput()
        else:
            self.fields["player_one_choice"].widget = forms.HiddenInput()

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.game = self.game

        if self.game.game_type == Game.PLAYER_VERSUS_COMPUTER:
            # autoplay the turn for the computer
            computer_choice = random.choice(
                [constants.ROCK, constants.SCISSOR, constants.PAPER]
            )
            instance.player_two_choice = computer_choice

        if (
            instance.player_one_choice is not None
            and instance.player_two_choice is not None
        ):
            # if they chose the same option, it's a TIE
            if instance.player_one_choice == instance.player_two_choice:
                instance.turn_result = GameTurn.PLAYER_TIE

            # check the scenarios for player one beating player two:
            # ROCK     beats    SCISSORS
            # SCISSORS beats    PAPER
            # PAPER    beats    ROCK
            elif (
                instance.player_one_choice == constants.ROCK
                and instance.player_two_choice == constants.SCISSOR
            ):
                instance.turn_result = GameTurn.PLAYER_ONE_WINS
            elif (
                instance.player_one_choice == constants.SCISSOR
                and instance.player_two_choice == constants.PAPER
            ):
                instance.turn_result = GameTurn.PLAYER_ONE_WINS
            elif (
                instance.player_one_choice == constants.PAPER
                and instance.player_two_choice == constants.ROCK
            ):
                instance.turn_result = GameTurn.PLAYER_ONE_WINS

            # If player one didn't beat player two on any of the choices, then player two wins by default!
            else:
                instance.turn_result = GameTurn.PLAYER_TWO_WINS

        if instance.turn_result is not None:
            if instance.turn_result in [
                GameTurn.PLAYER_ONE_WINS,
                GameTurn.PLAYER_TWO_WINS,
            ]:
                self.game.completed_at = timezone.now()

        # save the game so that the modified_date updates to reflect that we have had some action performed on it

        self.game.save()

        if commit:
            instance.save()

        return instance

rps/gameplay/views.py
import logging

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse

from rps.gameplay.forms import UserTurnForm
from rps.gameplay.models import Game

User = get_user_model()
logger = logging.getLogger(__name__)


def index(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    """The main gameplay page
    This page displays information about gameplay options and allows a
    user to select what type of game they wish to play
    """
    template = "gameplay/index.html"
    past_games = None
    count_past_games = 0

    if request.user.is_authenticated:
        past_games = request.user.past_games
        count_past_games = past_games.count()

    return render(
        request,
        template,
        {
            "count_past_games": count_past_games,
            "past_games": past_games,
        },
    )


@login_required
def new_game(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    """Create a new game depending on which option the user chose to play"""
    game_type = kwargs.get("game_type", None)
    user = request.user

    if game_type is not None and game_type in [
        Game.PLAYER_VERSUS_COMPUTER,
        Game.PLAYER_VERSUS_PLAYER,
    ]:
        try:
            game = Game.objects.create(game_type=game_type, player_one=user)
            messages.success(request, "Your new game is ready to play, good luck!")
            return redirect(reverse("gameplay:play", kwargs={"game_uuid": game.id}))
        except Exception as ex:
            logger.error(ex)
            messages.error(
                request,
                "There was an issue creating a new game, the site admins have been alerted, please try again later.",
            )
            return redirect(reverse("gameplay:index"))
    else:
        messages.error(
            request,
            "The requested new game type could not be located, please verify and retry.",
        )
        return redirect(reverse("gameplay:index"))


@login_required
def play(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    """The main gameplay page
    Allows the user to select their choice, and then waits for second user to play their turn
    """
    template = "gameplay/play.html"
    game_id = kwargs.get("game_uuid", None)
    user = request.user

    if Game.objects.filter(id=game_id).exists():
        game = Game.objects.get(id=game_id)
    else:
        messages.error(
            request,
            "The requested game could not be located, please verify you have the correct URL.",
        )
        return redirect(reverse("gameplay:index"))

    if request.method == "POST":
        form = UserTurnForm(request.POST, user=user, game=game)
        if form.is_valid():
            form.save()
            messages.success(request, "Your turn has been played!")
            return redirect(reverse("gameplay:play", kwargs={"game_uuid": game.id}))
    else:
        form = UserTurnForm(user=user, game=game)

    # get the winner of the game, if any, so we don't query the db multiple times in the html
    game_winner_info = game.game_winner_info

    return render(
        request,
        template,
        {
            "user": user,
            "game": game,
            "form": form,
            "game_winner_info": game_winner_info,
        },
    )

templates/gameplay/index.html
{% extends 'base.html' %}

{% block content %}
  {% if not request.user.is_authenticated %}
  <div class="alert alert-info">
    You must have an account and be signed in to Rock Paper Scissors prior to playing or creating a new game.
  </div>
  {% endif %}

  <h4>What type of game would you like to play?</h4>
  <h5 class="ms-3">
    <a href="{% url 'gameplay:new_game' 1 %}">
      Player Versus Player (PvP)
    </a>
  </h5>
  <h5 class="ms-3">
    <a href="{% url 'gameplay:new_game' 2 %}">
      Player Versus Computer (AI)
    </a>
  </h5>

  {% if request.user.is_authenticated %}
    <hr />
    <h3 class="mb-0">Your Game History</h3>
    {% if count_past_games == 0 %}
      <div class="alert alert-info">You have not yet played any games.</div>
    {% else %}
      <p>
        Click on the Created At date/time to view more details on the game.
      </p>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Created At (UTC)</th>
            <th>Player One</th>
            <th>Player Two</th>
            <th>Winner</th>
            <th>Last Played Turn At (UTC)</th>
            <th>Game Completed At (UTC)</th>
          </tr>
        </thead>
        <tbody>
          {% for game in past_games %}
            <tr>
              <td>
                <a href="{% url 'gameplay:play' game.id %}">
                  {{ game.created_at }}
                </a>
              </td>
              <td>{{ game.player_one.name }}</td>
              <td>{{ game.player_two.name|default:"Computer" }}</td>
              <td>{{ game.game_winner_info.name|default_if_none:"" }}</td>
              <td>{{ game.modified_at|default_if_none:"" }}</td>
              <td>{{ game.completed_at|default_if_none:"" }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% endif %}
  {% endif %}

{% endblock %}

templates/gameplay/play.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <h3>
    {% if game.game_winner_info is not None %}
      You played
    {% else %}
      Your are playing
    {% endif %}
    a {{ game.get_game_type_display }} Game
  </h3>

  {% if game_winner_info is not None %}
    <div class="alert alert-success">
      {% if game_winner_info.user == request.user %}
        Congratulations! You won this game!
      {% else %}
        We're sorry, {{ game_winner_info.name }} won this game.
      {% endif %}
    </div>
  {% else %}
    {% if game.which_players_turn is None or game.which_players_turn.user == request.user %}
      <form id="id_play_form" action="{% url 'gameplay:play' game.id %}" method="POST">{% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary btn-sm" type="submit">Submit Turn</button>
      </form>
    {% else %}
      <div class="alert alert-info">The second player has not yet played their turn.</div>
    {% endif %}
  {% endif %}

  {% if game.turns.all %}
    <hr />
    <h5 class="mb-0">Past Turns</h5>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Turn Started At (UTC)</th>
          <th>
            {% if game.player_one == request.user %}
              You
            {% else %}
              Player One
            {% endif %}
            Played
          </th>
          <th>
            {% if game.player_two == request.user %}
              You
            {% elif game.player_two is None %}
              Computer
            {% else %}
              Player Two
            {% endif %}
            Played
          </th>
          <th>
            Result
          </th>
        </tr>
      </thead>
      <tbody>
      {% for turn in game.turns.all %}
        <tr>
          <td>{{ turn.created_at }}</td>
          <td>{{ turn.get_player_one_choice_display|default:"Waiting" }}</td>
          <td>{{ turn.get_player_two_choice_display|default:"Waiting" }}</td>
          <td>{{ turn.get_turn_result_display|default:"" }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% endif %}
  <hr />
  <a href="{% url 'gameplay:index' %}" class="btn btn-warning">Back to Game Home</a>
{% endblock %}

templates/gameplay/result.html
{% extends 'base.html' %}

{% block content %}
  <h2>Game Result</h2>
{% endblock %}